import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { businesses, pathTitle, routes, updates } from '@/lib/site-data';
import { SearchBox } from '@/components/site-shell';

export function generateStaticParams() {
  return [...routes.map(item => ({ segments: item.path.slice(1).split('/') })), ...updates.map((_, i) => ({ segments: ['newsroom', `northstar-story-${i + 1}`] }))];
}

export async function generateMetadata({ params }: { params: Promise<{ segments: string[] }> }) {
  const { segments } = await params;
  const path = `/${segments.join('/')}`;
  const info = pathTitle(path) ?? (path.startsWith('/newsroom/') ? { title: 'Northstar story', description: 'An original sample story from Northstar Energy.', eyebrow: 'Newsroom' } : undefined);
  return info ? { title: info.title, description: info.description, alternates: { canonical: path } } : {};
}

export default async function ContentPage({ params, searchParams }: { params: Promise<{ segments: string[] }>; searchParams: Promise<{ q?: string }> }) {
  const { segments } = await params;
  const path = `/${segments.join('/')}`;
  const info = pathTitle(path);
  const isArticle = path.startsWith('/newsroom/') && segments.length === 2;
  if (!info && !isArticle) notFound();
  const page = info ?? { title: 'A Northstar perspective', description: 'Original demonstration content from Northstar Energy.', eyebrow: 'Media' };
  const query = (await searchParams).q?.toLowerCase().trim() ?? '';
  const isBusiness = path === '/business' || path.startsWith('/business/');
  const isRetail = path.endsWith('/retail');
  const isNews = path === '/newsroom' || path === '/media' || path.includes('press-releases') || path.includes('announcements') || isArticle;
  const isSearch = path === '/search';
  const isInvestors = path.startsWith('/investors');
  const cards = isBusiness ? businesses.map(([title, description]) => ({ title, description, href: `/business/${title.toLowerCase().replaceAll(' & ', '-').replaceAll(' ', '-')}` })) : isNews ? updates.map((x, i) => ({ title: x.title, description: `${x.type} · ${x.date} · Original sample article`, href: `/newsroom/northstar-story-${i + 1}` })) : isInvestors ? ['Reports & publications', 'Shareholder information', 'Dividends & meetings', 'Policies & governance', 'Market information', 'Investor guide'].map(title => ({ title, description: 'Demo information only. No live financial data is shown.', href: `/investors/${title.toLowerCase().replaceAll(' & ', '-').replaceAll(' ', '-')}` })) : [];
  const searchItems = routes.filter(x => `${x.title} ${x.description}`.toLowerCase().includes(query));

  return <main id="main-content">
    <section className="page-hero"><div className="page-hero-art"/><div className="wrap page-hero-content"><div className="breadcrumb"><Link href="/">Home</Link><span>/</span>{segments.map((part, i) => <span key={part}>{i > 0 && <i>/</i>}{part.replaceAll('-', ' ')}</span>)}</div><span className="eyebrow eyebrow-light">{page.eyebrow}</span><h1>{page.title}</h1><p>{page.description}</p>{isRetail && <span className="demo-pill">Sample retail experience · demo</span>}</div><span className="page-hero-code">N / ENERGY SYSTEMS</span></section>

    {isSearch ? <section className="section"><div className="wrap narrow"><div className="section-head"><div><span className="eyebrow">Find your way</span><h2>What can we help you find?</h2><p>Search pages and resources across this demonstration website.</p></div></div><SearchBox/>{query && <div className="search-results"><h3>{searchItems.length} results for “{query}”</h3>{searchItems.map(item => <Link className="result-row" href={item.path} key={item.path}><div><span className="eyebrow">{item.eyebrow}</span><h3>{item.title}</h3><p>{item.description}</p></div><b>↗</b></Link>)}{searchItems.length === 0 && <p>No pages matched that search. Try “business”, “sustainability” or “careers”.</p>}</div>}</div></section>
      : isArticle ? <section className="section"><article className="wrap article-wrap"><span className="eyebrow">Sample story · September 2026</span><h2>Designing energy systems around the communities they serve</h2><div className="article-image"><Image src="/images/facility.svg" alt="Original illustration of a connected energy facility" fill sizes="(max-width: 900px) 100vw, 900px"/></div><p className="lead">Strong energy systems start with understanding the places and people they support. This original sample article explores how teams can bring local insight into long-term planning.</p><p>Across the sector, infrastructure is changing alongside expectations. Communities want dependable services, clearer information and a meaningful part in decisions that shape their future. That makes listening an essential part of good planning.</p><p>Northstar is an independent learning project. This story and all names, details and dates on this site are fictional sample content.</p><Link href="/newsroom" className="text-link">← Back to newsroom</Link></article></section>
      : <>
        <section className="section content-intro"><div className="wrap two-col"><div><span className="eyebrow">Northstar perspective</span><h2>Energy is a shared story.</h2></div><div><p className="lead">We take a connected view of essential energy: the infrastructure that supports it, the people who make it work and the ideas that can help it evolve.</p><p>This independent portfolio demonstration uses original sample content. It does not represent or make claims on behalf of any real company.</p><Link className="text-link" href="/about/who-we-are">About this project <span>↗</span></Link></div></div></section>
        {isBusiness && <section className="section compact"><div className="wrap"><div className="section-head"><div><span className="eyebrow">Capabilities</span><h2>One network. Many possibilities.</h2><p>Explore original concept descriptions across a broad energy portfolio.</p></div></div><div className="business-grid route-grid">{businesses.map(([title, description], i) => <Link href={`/business/${['refineries','retail','lpg','lubricants','aviation','direct-sales','projects-pipelines','engineering-projects','natural-gas-renewables','petrochemicals','research-development','international-trade'][i]}`} className="business-card" key={title}><span className="business-no">{String(i + 1).padStart(2, '0')}</span><span className="business-symbol">{['◒','⌁','◉','◇','↗','⌘'][i % 6]}</span><h3>{title}</h3><p>{description}</p><span className="card-arrow">↗</span></Link>)}</div></div></section>}
        {isRetail && <section className="section"><div className="wrap"><div className="section-head"><div><span className="eyebrow">Customer services</span><h2>Useful services, close at hand.</h2><p>These examples are interface concepts only; no actual locations, prices or service availability are provided.</p></div></div><div className="service-grid">{[['Find a service point','Demo locator UI · location data is not connected'],['Fuel information','Sample price panel · no live prices displayed'],['On-the-road support','Demo emergency information · contact local services for assistance']].map(([a,b]) => <div className="service-card" key={a}><span>↗</span><h3>{a}</h3><p>{b}</p><button type="button">Sample interface <b>→</b></button></div>)}</div></div></section>}
        {isInvestors && <section className="section"><div className="wrap"><div className="notice"><span>DEMO INFORMATION</span><p>This independent project does not publish real financial results, share prices, dividends or investment recommendations. Investor pages contain navigation and sample content only.</p></div><div className="link-grid">{cards.map(c => <Link className="link-card" href={c.href} key={c.title}><span className="eyebrow">Investor resources</span><h3>{c.title}</h3><p>{c.description}</p><b>↗</b></Link>)}</div></div></section>}
        {isNews && <section className="section"><div className="wrap"><div className="section-head"><div><span className="eyebrow">Editorial · Sample content</span><h2>Stories from across the network.</h2><p>Original demonstration articles. Not official announcements or company news.</p></div><Link href="/media/announcements" className="text-link">Announcements <span>↗</span></Link></div><div className="news-grid">{updates.map((item, i) => <article className="news-card" key={item.title}><div className="news-visual"><span className="news-visual-mark">N / 0{i + 1}</span><span className="news-date">{item.date}</span></div><div className="news-content"><span className="eyebrow">{item.type} · Demo</span><h3>{item.title}</h3><Link href={`/newsroom/northstar-story-${i + 1}`}>Read story <span>↗</span></Link></div></article>)}</div></div></section>}
        {path === '/contact' || path === '/complaints-feedback' ? <section className="section"><div className="wrap contact-grid"><div><span className="eyebrow">Start a conversation</span><h2>We’d like to hear from you.</h2><p>This demonstration form is not connected to a backend. Do not submit personal or sensitive information.</p><p><b>General enquiries</b><br/>hello@northstar.example<br/>Example address, India</p><p><b>Independent project</b><br/>All company details are sample content.</p></div><form className="contact-form" action="/contact" method="get"><label>Name<input required name="name" placeholder="Your name"/></label><label>Email<input required type="email" name="email" placeholder="you@example.com"/></label><label>Department<select name="department"><option>General enquiry</option><option>Careers</option><option>Investor information</option><option>Business partnership</option></select></label><label>Subject<input name="subject" placeholder="How can we help?"/></label><label className="full-field">Message<textarea rows={4} name="message" placeholder="Write your message"/></label><button className="button button-navy">Submit demo form <span>↗</span></button></form></div></section> : null}
        {!isBusiness && !isNews && !isRetail && !isInvestors && path !== '/contact' && path !== '/complaints-feedback' && <section className="section"><div className="wrap feature-grid"><div className="feature-image"><Image src="/images/facility.svg" alt="Original illustration of an energy facility" fill sizes="(max-width: 800px) 100vw, 52vw"/></div><div><span className="eyebrow">A practical point of view</span><h2>Progress happens together.</h2><p>Good outcomes come from combining expertise, staying curious and making space for different perspectives. Our teams bring these principles into the way they think about operations and long-term opportunity.</p><p>From infrastructure and customer experience to community partnership, each part of the system has a role to play.</p><Link href="/sustainability" className="button button-navy">Explore our approach <span>↗</span></Link></div></div></section>}
        <section className="section related-section"><div className="wrap"><div className="section-head"><div><span className="eyebrow">Keep exploring</span><h2>More from Northstar.</h2><p>Find related information and sample resources.</p></div></div><div className="link-grid">{(cards.length ? cards.slice(0, 6) : [{ title: 'Our businesses', description: 'Explore our connected energy capabilities.', href: '/business' }, { title: 'Sustainability', description: 'Our approach to people, planet and progress.', href: '/sustainability' }, { title: 'Get in touch', description: 'Find a team or share your feedback.', href: '/contact' }]).map(c => <Link className="link-card" href={c.href} key={c.title}><span className="eyebrow">Explore</span><h3>{c.title}</h3><p>{c.description}</p><b>↗</b></Link>)}</div></div></section>
      </>}
    <section className="bottom-cta"><div className="wrap bottom-cta-inner"><div><span className="eyebrow eyebrow-light">A shared horizon</span><h2>Let’s move the conversation forward.</h2></div><Link href="/contact" className="button button-light">Get in touch <span>↗</span></Link></div></section>
  </main>;
}
