import Image from 'next/image';
import Link from 'next/link';
import { businesses, updates } from '@/lib/site-data';

function SectionHead({ eyebrow, title, text, href, link }: { eyebrow: string; title: string; text: string; href?: string; link?: string }) {
  return <div className="section-head"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{text}</p></div>{href && <Link className="text-link" href={href}>{link ?? 'Explore more'} <span>↗</span></Link>}</div>;
}

export default function HomePage() {
  return <main id="main-content">
    <section className="hero-home"><Image src="/images/hero-energy.svg" alt="Original illustration of an energy facility at dusk" fill priority sizes="100vw" className="hero-image"/><div className="hero-shade"/><div className="wrap hero-content"><div className="hero-copy"><span className="hero-tag"><i/> AN INDEPENDENT ENERGY GROUP</span><h1>Energy that moves<br/><em>life forward.</em></h1><p>We bring people, ideas and infrastructure together to build a more resilient energy future.</p><div className="hero-actions"><Link href="/about" className="button button-light">Discover Northstar <span>↗</span></Link><Link href="/sustainability" className="button button-glass">Our transition <span>↗</span></Link></div></div><div className="hero-index"><span>01</span><span className="hero-line"/><span>01 / 03</span></div></div><div className="hero-caption">DEMO VISUAL · ORIGINAL ILLUSTRATION</div></section>

    <section className="ticker"><div className="wrap ticker-inner"><span className="ticker-label"><i/> COMPANY NOTES</span><div className="ticker-story">Northstar shares a discussion paper on practical transition pathways <span>·</span> September 2026</div><Link href="/newsroom">All updates <b>↗</b></Link></div></section>

    <section className="section intro-section"><div className="wrap intro-grid"><div className="intro-photo"><Image src="/images/facility.svg" alt="Original illustration of an energy and infrastructure facility" fill sizes="(max-width: 760px) 100vw, 50vw"/><span className="photo-note">A connected energy landscape · Demo artwork</span></div><div className="intro-copy"><span className="eyebrow">A broader view of energy</span><h2>Built on experience.<br/><em>Open to what’s next.</em></h2><p>Northstar is an independent corporate energy concept. We are interested in the systems that connect essential services today with more responsible choices for tomorrow.</p><p>Across infrastructure, customer services and emerging solutions, progress begins by listening, learning and working together.</p><Link href="/about/who-we-are" className="button button-navy">Who we are <span>↗</span></Link><div className="values-row"><span>01 <b>Responsibility</b></span><span>02 <b>Ingenuity</b></span><span>03 <b>Partnership</b></span></div></div></div></section>

    <section className="section business-section"><div className="wrap"><SectionHead eyebrow="Our capabilities" title="Connected by purpose." text="A diverse portfolio of capabilities helps us respond to the changing needs of people, businesses and communities." href="/business" link="Explore our businesses"/><div className="business-grid">{businesses.slice(0, 6).map(([title, desc], i) => <Link href={`/business/${['refineries','retail','lpg','lubricants','aviation','natural-gas-renewables'][i]}`} className="business-card" key={title}><span className="business-no">0{i + 1}</span><span className="business-symbol">{['◒','⌁','◉','◇','↗','⌘'][i]}</span><h3>{title}</h3><p>{desc}</p><span className="card-arrow">↗</span></Link>)}</div><div className="center-link"><Link className="text-link" href="/business">View all business areas <span>↗</span></Link></div></div></section>

    <section className="transition-section"><div className="wrap transition-grid"><div><span className="eyebrow eyebrow-light">Progress with perspective</span><h2>A thoughtful transition<br/>takes all of us.</h2><p>We believe that a durable energy future needs practical action, open collaboration and attention to the communities at its heart.</p><Link href="/sustainability" className="button button-light">Our approach <span>↗</span></Link></div><div className="transition-aside"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="orbit-core">N<span>↗</span></div><div className="orbit-label label-a">People</div><div className="orbit-label label-b">Planet</div><div className="orbit-label label-c">Progress</div><small>OUR SUSTAINABILITY FRAMEWORK · DEMO</small></div></div></section>

    <section className="section stats-section"><div className="wrap"><SectionHead eyebrow="The Northstar idea" title="Built to connect." text="A portfolio concept shaped around shared capability, long-term thinking and measurable action."/><div className="stats-grid"><div><strong>XX<span>+</span></strong><p>Connections across the value chain</p></div><div><strong>XX</strong><p>Years of collective experience · demo</p></div><div><strong>XX<span>%</span></strong><p>Transition ambition · sample only</p></div><div><strong>XX</strong><p>Ideas moving into action</p></div></div><p className="demo-note">All figures shown are placeholders for demonstration purposes.</p></div></section>

    <section className="section updates-section"><div className="wrap"><SectionHead eyebrow="Perspectives & updates" title="The latest from Northstar." text="Original sample stories about the people, ideas and work shaping our direction." href="/newsroom" link="Visit newsroom"/><div className="news-grid">{updates.map((item, i) => <article className={`news-card news-${i + 1}`} key={item.title}><div className="news-visual"><span className="news-visual-mark">{['N / 01','FIELD NOTES','IDEAS IN MOTION'][i]}</span><span className="news-date">{item.date}</span></div><div className="news-content"><span className="eyebrow">{item.type} · Sample story</span><h3>{item.title}</h3><Link href="/newsroom">Read the story <span>↗</span></Link></div></article>)}</div></div></section>

    <section className="section pathways-section"><div className="wrap pathway-grid"><div><span className="eyebrow">Work with meaning</span><h2>Bring your perspective<br/>to the energy story.</h2><p>Curious people with different experiences help build stronger teams. Discover what a career in this independent demonstration company could look like.</p><Link href="/careers" className="button button-navy">Explore careers <span>↗</span></Link></div><div className="pathway-card"><span className="eyebrow">For partners & investors</span><h3>Good work moves further when we work together.</h3><Link href="/quick-links">Explore opportunities <span>↗</span></Link><Link href="/investors">Investor information <span>↗</span></Link><Link href="/contact">Start a conversation <span>↗</span></Link></div></div></section>

    <section className="gallery-strip"><div className="wrap gallery-inner"><div><span className="eyebrow eyebrow-light">A closer look</span><h2>Ideas take shape<br/>in the field.</h2><p>Explore original demo illustrations of connected energy infrastructure.</p><Link href="/media/gallery" className="button button-light">Photo gallery <span>↗</span></Link></div><div className="gallery-tile tile-one"><span>CONNECTED SYSTEMS</span></div><div className="gallery-tile tile-two"><span>PEOPLE & POSSIBILITY</span></div><div className="gallery-tile tile-three"><span>BUILDING TOMORROW</span></div></div></section>
  </main>;
}
